# Generated by Django 4.0.4 on 2022-12-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Space Beaver', 'Space Beaver'), ('Book', 'Book'), ('Others', 'Others')], default='Others', max_length=12),
            preserve_default=False,
        ),
    ]
