# Generated by Django 4.0.4 on 2022-12-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cartproduct_price_alter_cartproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='price_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
